#!/bin/bash
set -euo pipefail

usage() {
echo \
"
MEMO - toolkit
Usage: memo <commmand> [options]

MEMO commands:
   index  - index pangenome into MEMO membership or conservation indexes
   query  - query k-mer membership or conservation on pivot genome region
   view   - plot sequence conservation
"
exit 0
}

if [ "$#" -eq 0 ] || [ "$1" = "-h" ]; then
    usage
fi

# get subcommand
SUBCOMMAND=$1; shift

# run subcommand
case $SUBCOMMAND in

  # Index region
  index)
    ./index.sh "$@"
    ;;

  # Query region
  query)
    ./query.sh "$@"
    ;;

  # Query region
  view)
    ./view.sh "$@"
    ;;

  *)
    echo -e "Error unrecognized command:" $SUBCOMMAND "\n"
    usage
    ;;
esac
