#!/bin/bash
set -euo pipefail

usage() {
echo \
"
omem: order mem toolkit
Usage: omem <commmand> [options]

Main omem commands:
  -- index         index overlap order MEMs from a document array profile
  -- extract       extract region chr:start-end from overlap order MEM index
  -- query         query k-mers on order MEMs of input bed file region
"
exit 0
}

if [ "$#" -eq 0 ] || [ "$1" = "-h" ]; then
    usage
fi

# get subcommand
SUBCOMMAND=$1; shift

# run subcommand
case $SUBCOMMAND in

  # Index region
  index)
    ./index.sh "$@"
    ;;

  # Extract region
  extract)
    ./extract.sh "$@"
    ;;

  # Query region
  query)
    ./query.sh "$@"
    ;;

  *)
    echo -e "Error unrecognized command:" $SUBCOMMAND "\n"
    usage
    ;;
esac

